### ISSUE TITLE
Create modifiers specific to the game

### ISSUE THREAD

**Issue by radl97** [adrianrobotka/VectorCar#13]
Force (friction, gravity, etc.)
Velocity overwrite (after perfect collision) -> How do we display the force? (because it is one)
Position overwrite (two objects interpenetrating) -> We also need to calculate a normal force (kenyszerero, nyomoero), otherwise we wouldn't be able to calculate the friction

**Comment by adrianrobotka** [comment]
This is obsolite, the features are changed.
