### ISSUE TITLE
Make the OptionsActivity

### ISSUE THREAD

**Issue by maxxik** [adrianrobotka/VectorCar#28]
Find out what can be set in the options menu, and do it

**Comment by adrianrobotka** [comment]
e.g. set lane number and difficulty

**Comment by maxxik** [comment]
number of lanes and max speed is customizable

**Comment by maxxik** [comment]
do we need to store the optinons values? (e.g. savedInstance)

**Comment by maxxik** [comment]
Issue.finish(); ?
